id: I3A83745B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T06:49:46+00:00'
last_modified: '2022-06-08T05:03:38.442303+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20482
  title: མཛོད་འགྲེལ་མངོན་པའི་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B769:
      image_group_id: I4694
      title: ''
      total_pages: 782
      order: 1
      base_file: B769.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
