id: P005579
initial_creation_type: ocr
source_metadata:
  id: bdr:W20482
  title: མཛོད་འགྲེལ་མངོན་པའི་རྒྱན
  author: ''
  volumes:
    7371b7a405d447f683eeda26de87e466:
      image_group_id: I4694
      title: ''
      volume_number: 1
      total_pages: 782
